### ISSUE TITLE
Wrong parse elf section on MIPS

### ISSUE THREAD

**Issue by GH0st3rs** [plasma-disassembler/plasma#92]
```
# plasma -i /mnt/usr/bin/ssid
Traceback (most recent call last):
  File "/usr/sbin/plasma", line 11, in <module>
    load_entry_point('plasma==1.0', 'console_scripts', 'plasma')()
  File "/usr/lib/python3.7/site-packages/plasma-1.0-py3.7-linux-x86_64.egg/plasma/main.py", line 35, in console_entry
    if not gctx.load_file():
  File "/usr/lib/python3.7/site-packages/plasma-1.0-py3.7-linux-x86_64.egg/plasma/lib/__init__.py", line 197, in load_file
    self.db)
  File "/usr/lib/python3.7/site-packages/plasma-1.0-py3.7-linux-x86_64.egg/plasma/lib/disassembler.py", line 102, in __init__
    self.load_symbols()
  File "/usr/lib/python3.7/site-packages/plasma-1.0-py3.7-linux-x86_64.egg/plasma/lib/disassembler.py", line 160, in load_symbols
    self.binary.load_dyn_sym()
  File "/usr/lib/python3.7/site-packages/plasma-1.0-py3.7-linux-x86_64.egg/plasma/lib/fileformat/elf.py", line 207, in load_dyn_sym
    tagstr = self.__translate_dynamic_tag(tag.entry.d_tag)
  File "/usr/lib/python3.7/site-packages/plasma-1.0-py3.7-linux-x86_64.egg/plasma/lib/fileformat/elf.py", line 190, in __translate_dynamic_tag
    return self.dynamic_tag_translation[tag]
KeyError: 1879048245
```
I can send testing elf file on your email, if you want

**Comment by GH0st3rs** [comment]
No longer relevant
